### ISSUE TITLE
model resconstruction fails (problem with ADT and predicates)

### ISSUE THREAD

**Issue by dzufferey** [wies/grasshopper#45] opened 2020-05-25 16:18 UTC
Getting a `Not_found` with `-model`. It seems to come from ADT and predicates.
Here is a small example:
```
include "tests/spl/adt/lists.spl"

struct Node {
  var next: Node;
}

predicate lseg(x: Node, y: Node, lst: List) {
  (x == y &*& lst == nil) ||
  (x != y &*& lst != nil &*& acc(x) &*& lseg(x.next, y, lst.tl))
}

predicate list(x: Node, lst: List) {
  lseg(x, null, lst)
}

procedure yada()

procedure main(n: Node, ghost lst: List)
  requires list(n, lst)
  ensures list(n, lst)
{
  assert list(n, lst) ;
  yada();
  assert list(n, lst) ;
}
```
running it I get:
```
./grasshopper.native adt.spl -v -model model.html -procedure main
...
...
Checking procedure main...
	main_assert_22_2.
	main_assert_24_2.
Fatal error: exception Not_found
```

If I replace `list(n, lst)` by `lseg(n, null, lst)` the error disappear. If I remove the `List` the error disappear as well.

**Comment by wies** [comment] 2020-05-25 16:57
Interestingly, I had a pending commit related to model reconstruction that seems to have fixed the issue (or I can't reproduce it). Can you please check whether the issue is resolved with the latest commit?

**Comment by dzufferey** [comment] 2020-05-25 17:01
I tried to clean and rebuild both on the master and actris branch. I still get the error.
I'm using z3 4.8.8

**Comment by wies** [comment] 2020-05-25 22:02
I can reproduce the error with the latest Z3 version. I'll look into it.

**Closed** 2020-05-26 23:21 UTC
