### ISSUE TITLE
Congruence closure doesn't know ADT constructor equalities?

### ISSUE THREAD

**Issue by siddharth-krishna** [wies/grasshopper#28] opened 2018-11-02 23:02 UTC
Example program (add to `tests/reloc/b-link.spl` in `symb-exec` branch):
```
procedure aaa(x: Node) returns (I: Interface)
  requires hrepSpatial(x)
  ensures hrepSpatial(x)
{
  var xfm: Map<Node, Map<Node, FlowDom>>;
  xfm := { n: Node :: { n1: Node :: domZero() } };
  xfm := xfm[x := xfm[x][x.next := fd({ k: K :: 0 }, { k: K :: 0 })]];
  I := int(I.inf, I.na, xfm, I.FP, I.FPo);
  pure assert forall n: Node, n1: Node, k: K :: I.fm[n][n1].ks[k] == 0;
}
```

We can infer that `I.fm[x][x.next].ks == compr^3` from the following clauses in the VC:
```
compr^3 == fd(compr^3, compr^2).ks
(x.compr^1[sk_v^2 := fd(compr^3, compr^2)][sk_v^2] == fd(compr^3, compr^2))
xfm == compr^1[x := x.compr^1[sk_v^2 := fd(compr^3, compr^2)]]
I.fm == xfm
```
But the definition of `compr^3` is not instantiated because the term `compr^3[k]` does not exist, even though `I.fm[n][n1].ks[k]` exists.

**Comment by wies** [comment] 2018-11-03 16:48
Thanks. I first fixed the problem with x.next in the VC backend (it was always checking field writes on maps of the type Map<Loc<T>, S> irregardless of whether that map was actually a field that is part of the state).

Here is a simplified program that has the same problem:

```
type K;

struct Node {
  var next: Node;
}

datatype Interface =
  int(fm: Map<Node, FlowDom>)
  | intUndef; // For when compositions don't exist

pure function domZero() returns(p: FlowDom)
  ensures forall k: K :: p.ks[k] == 0

options "-propreads"

datatype FlowDom = fd(ks: Map<K, Int>)

procedure aaa(x: Node) returns (I: Interface)
  requires acc(x)
  ensures acc(x)
{
  var xfm: Map<Node, FlowDom>;
  xfm := { n: Node ::  domZero() };
  xfm := xfm[x := fd({ k: K :: 0 })];
  I := int(xfm);
  var n: Node;
  var n1: Node;
  var k: K;
  pure assert I.fm[n].ks[k] == 0;
}
```

I think the problem is that the map write introduces a disjunction over which we currently don't propagate nested map reads. I'll have to think about how to fix this.

**Comment by wies** [comment] 2018-11-03 22:44
I pushed a fix for this issue by adding additional term generators for read term propagation that handle these cases. The problem will reoccur if we build more deeply nested maps. So we'll have to think about a more robust solution in the long term.

**Closed by wies** 2018-11-03 22:44 UTC

**Comment by siddharth-krishna** [comment] 2018-11-05 03:59
This works, thanks!
