### ISSUE TITLE
Type declaration bug in SMT queries for ADTs

### ISSUE THREAD

**Issue by siddharth-krishna** [wies/grasshopper#15] opened 2018-01-18 17:46 UTC
If we have an ADT that contains an ADT, like
```
datatype Pair = pair(fst: Int, snd: Int);

datatype Interface =
  int(p: Pair);

procedure test0(I: Interface)
  requires I.p.fst == 3
  ensures I.p.fst != 2
{}
```

Then the generated SMT query looks like
```
...
(declare-sort Pair 0)
(declare-datatypes () ( (Interface (int (p Pair)))))
(declare-fun I$0 () Interface)
(declare-fun Label$0 () Bool)

(assert (and (= (fst (p I$0)) 2) Label$0))
(assert (= (fst (p I$0)) 3))
(assert (= 3 2))
(assert (= 3 (fst (p I$0))))
(check-sat)
```

Which produces an SMT error:
`Fatal error: exception SmtLibSolver.SmtLib_error(_, "SmtLib: \"line 19 column 28: unknown function/constant fst")`

It looks like types inside ADT declarations are being treated as normal sorts, somehow?

**Comment by wies** [comment] 2018-01-18 20:28
Mutually recursive datatype declarations are not yet supported fully. I committed a partial fix in language-improvements that should let you do a workaround. The problem is that currently the back-end needs to see all ADT sort declarations at the top-level (i.e. not nested within some other ADT sort declarations). The following variant of your example should now work, though:

```
datatype Pair = pair(fst: Int, snd: Int);

datatype Interface =
  int(p: Pair);

procedure test0(I: Interface, y: Pair)
  requires I.p.fst == 3 && y == y
  ensures I.p.fst != 2
{}
```

**Comment by siddharth-krishna** [comment] 2018-01-20 21:20
Thanks! I tried to use the workaround but now I've run into a (potentially unrelated) issue. The modified example:
```
datatype Pair = pair(fst: Int, snd: Int);

datatype Interface =
  int(m: Map<Int, Pair>);

procedure test0(I: Interface, q: Pair)
  requires I.m[2].fst == 3 && q == q
  ensures I.m[2].fst != 2
{}
```

Produces the error:
```
Fatal error: exception SmtLibSolver.SmtLib_error(_, "SmtLib: \"line 26 column 33: unknown sort 'Pair'")
```

And the SMT file looks like this:
```
...
(declare-datatypes
                   () ( (Pair (pair (fst Int) (snd Int))) (Interface (int (m
                        (Map Int Pair))))))
...
```

Btw, is Z3 not using the SMT-lib 2.6 syntax for ADTs? I was trying to figure out what the above definition should be to make Z3 happy, but couldn't find Z3's syntax documented anywhere.

**Comment by wies** [comment] 2018-01-20 22:10
Hmm, it seems that SMT-LIB does not allow Pair to be used as a parameter to the type constructor Map in the ADT declaration. The following works:

```
(declare-datatypes () ( (Pair (pair (fst Int) (snd Int))))
(declare-datatypes () ( (Interface (int (m (Map Int Pair))))))
```

I'll try to get this fixed.

**Closed** 2018-03-23 03:42 UTC
Labels: bug
