### ISSUE TITLE
141: silent failures that look like successful verification

### ISSUE THREAD

**Issue by siddharth-krishna** [wies/grasshopper#6] opened 2016-05-03 22:43 UTC
On commit `6b5e120` on the master branch, I came across this strange bug:

```
$ ./grasshopper.native -v tests/spl/link_and_array/btree_generic.spl -procedure find -smtsolver z3+cvc4
GRASShopper version 0.3
Selected SMT solvers: Z3, CVC4
Inferring accesses, eliminating loops, arrays, new/dispose, and global dependencies.
Eliminating SL, adding heap access checks.
Eliminating return statements and transforming to SSA form.
Checking procedure find_loop...
Checking VC: find_loop_check_heap_access_165_13.
Checking VC: find_loop_precondition_of_findIt_165_13.
Checking VC: find_loop_check_heap_access_167_6.
Checking VC: find_loop_check_heap_access_167_6.
Checking VC: find_loop_check_heap_access_172_8.
Checking VC: find_loop_check_heap_access_172_8.
Checking VC: find_loop_check_heap_access_174_6.
Checking VC: find_loop_check_heap_access_174_6.
Checking VC: find_loop_ghost_field_invariant_for_parent_176_3.
Checking VC: find_loop_invariant_176_3.
$
```

This makes it look like the program is successfully verified, but I was wondering why it verified procedure `find_loop` and ignored `find`. The return code was:

```
$ echo $?
141
```

This seems to be related to CVC4 somehow, for when I remove that option it goes through. Any idea what's going on?

**Comment by wies** [comment] 2016-05-03 23:12
It seems like for some reason it is silently crashes. Given that this only occurs if CVC4 is used, I suspect that the problem is related to the communication with the child process running CVC4.

**Comment by wies** [comment] 2018-01-18 04:56
I haven't seen this issue in quite a while, so I assume that it has been fixed upstream in CVC4. I am closing this issue. We can reopen if the problem reoccurs.

**Closed by wies** 2018-01-18 04:56 UTC
Labels: bug
